name: fiura_ecosystem
description: A new Flutter project.
<<<<<<< HEAD

publish_to:

=======
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


>>>>>>> master
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

<<<<<<< HEAD
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0


=======
  #NAVIGATION
  auto_route: ^5.0.2
  url_strategy: ^0.2.0

  #LOGIC
  flutter_bloc: ^8.1.1
  freezed: ^2.3.2
  get_it: ^7.2.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
>>>>>>> master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
<<<<<<< HEAD
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  freezed: ^2.2.1

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

=======
  very_good_analysis: ^3.1.0
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.2
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true

  assets:
    - assets/

analyzer:
  errors:
    invalid_annotation_target: ignore
>>>>>>> master
